session_metrics_enabled: true
custom_pages:
  metrics:
    rows:
      - columns:
          - width: 8
            widgets:
              - "metrics/metrics"
  partition:
    rows:
      - columns:
          - width: 8
            widgets:
              - "cluster/partitions"

